--------------------------------------------------------
--  Datei erstellt -Sonntag-April-21-2019   
--------------------------------------------------------
DROP SEQUENCE "FLIGHT_DEV"."ADR_ADDRESS_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."ADR_ADDRESS_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."ADR_CITY_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."ADR_CITY_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."ADR_COUNTRY_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."ADR_COUNTRY_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."APL_ENGINE_TYPE_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."APL_MAINT_PROGR_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."APL_MAINT_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."APL_PLANE_MODELL_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."APL_PLANE_MODELL_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."APL_PLANE_MODELL_SEQ2";
DROP SEQUENCE "FLIGHT_DEV"."APL_PLANE_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."APL_PLANE_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."APL_PLANE_SEQ2";
DROP SEQUENCE "FLIGHT_DEV"."APL_PLANE_TYPE_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."APL_PLANE_TYPE_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."APL_PLANE_TYPE_SEQ2";
DROP SEQUENCE "FLIGHT_DEV"."ARP_AIRPORT_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."ARP_AIRPORT_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."BAK_BANKACCOUNT_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."BAK_BANKACCOUNT_TYPE_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."BAS_BASIC_GRP_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."BAS_BASIC_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."BAS_BASIC_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."BAS_BASIC_SEQ2";
DROP SEQUENCE "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY_ADD_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY_ADD_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY_GRP_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."BOR_BORD_LOG_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."BOR_BORD_LOG_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."BOR_BORD_LOG_SEQ2";
DROP SEQUENCE "FLIGHT_DEV"."BOR_BORD_LOG_SEQ3";
DROP SEQUENCE "FLIGHT_DEV"."COM_COMPANY_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."CON_CONTACT_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."CON_CONTACT_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."CON_CONTACT_TYPE_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."COST_COST_GRP_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."DEPT_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."DOC_DOCUMENT_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."DOC_DOCUMENT_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."DOC_DOCUMENT_TYPE_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."DOC_DOCUMENT_TYPE_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."DOC_USAGE_TYPE_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."DOC_USAGE_TYPE_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."EMP_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."FLI_FLIGHT_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."FLI_FLIGHT_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."FLI_FLIGHT_SEQ2";
DROP SEQUENCE "FLIGHT_DEV"."MDT_MANDANT_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."MDT_MANDANT_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."MDT_MANDANT_SEQ2";
DROP SEQUENCE "FLIGHT_DEV"."ORG_ORG_UNIT_REL_TYPE_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."ORG_ORG_UNIT_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."ORG_ORG_UNIT_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."ORG_ORG_UNIT_TYPE_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."ORG_UNIT_CHECK_OUT_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."ORG_UNIT_REL_TYPE_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."ORG_UNIT_REL_TYPE_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."ORG_UNIT_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."ORG_UNIT_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."ORG_UNIT_SEQ2";
DROP SEQUENCE "FLIGHT_DEV"."ORG_UNIT_TYPE_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."REL_BORD_LOG_ENTRY_PAY_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."REL_CONTACT_ADDRESS_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."REL_CONTACT_BANKACCOUNT_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."REL_DOC_CONTACT_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."REL_DOC_TYPE_USAGE_TYPE_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."REL_ORG_UNIT_CON_CON_TYPE_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."REL_ORG_UNIT_CON_ORG_REL_TYPE1";
DROP SEQUENCE "FLIGHT_DEV"."REL_ORG_UNIT_CON_ORG_TYPE_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."REL_ORG_UNIT_CON_ORG_TYPE_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."REL_ORG_UNIT_CON_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."REL_ORG_UNIT_CONTACT_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."REL_ORG_UNIT_CONTACT_SEQ1";
DROP SEQUENCE "FLIGHT_DEV"."REL_ORG_UNIT_CONTACT_SEQ2";
DROP SEQUENCE "FLIGHT_DEV"."REL_ORG_UNIT_ORG_REL_TYPE_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."REL_PLANE_FLIGHT_CHARTERER_SE";
DROP SEQUENCE "FLIGHT_DEV"."REL_PLANE_FLIGHT_CHARTERER_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."REL_PLANE_FLIGHT_SEQ";
DROP SEQUENCE "FLIGHT_DEV"."RES_RESERVATION_SEQ";
DROP TABLE "FLIGHT_DEV"."ADR_ADDRESS" cascade constraints;
DROP TABLE "FLIGHT_DEV"."ADR_CITY" cascade constraints;
DROP TABLE "FLIGHT_DEV"."ADR_COUNTRY" cascade constraints;
DROP TABLE "FLIGHT_DEV"."APL_ENGINE_TYPE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."APL_MAINT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."APL_MAINT_PROGR" cascade constraints;
DROP TABLE "FLIGHT_DEV"."APL_PLANE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."APL_PLANE_MODELL" cascade constraints;
DROP TABLE "FLIGHT_DEV"."APL_PLANE_TYPE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."ARP_AIRPORT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."BAK_BANKACCOUNT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."BAK_BANKACCOUNT_TYPE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."BAS_BASIC" cascade constraints;
DROP TABLE "FLIGHT_DEV"."BAS_BASIC_GRP" cascade constraints;
DROP TABLE "FLIGHT_DEV"."BOR_BORD_LOG" cascade constraints;
DROP TABLE "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY" cascade constraints;
DROP TABLE "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY_ADD" cascade constraints;
DROP TABLE "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY_GRP" cascade constraints;
DROP TABLE "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY_HOB_RPM" cascade constraints;
DROP TABLE "FLIGHT_DEV"."CON_CONTACT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."CON_CONTACT_TYPE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."COST_COST_GRP" cascade constraints;
DROP TABLE "FLIGHT_DEV"."DEPT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."DOC_DOCUMENT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."DOC_DOCUMENT_TYPE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."DOC_USAGE_TYPE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."EMP" cascade constraints;
DROP TABLE "FLIGHT_DEV"."FLI_FLIGHT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."FLI_FLIGHT_COMMENTS" cascade constraints;
DROP TABLE "FLIGHT_DEV"."FLI_FLIGHT_DISCOUNT_REASONS" cascade constraints;
DROP TABLE "FLIGHT_DEV"."FLI_FLIGHT_DISCOUNTS" cascade constraints;
DROP TABLE "FLIGHT_DEV"."GAL_GAIN_AND_LOSS" cascade constraints;
DROP TABLE "FLIGHT_DEV"."HAN_HANGAR" cascade constraints;
DROP TABLE "FLIGHT_DEV"."INV_INVOICE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."INV_INVOICE_TYPE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."LAN_LANDING" cascade constraints;
DROP TABLE "FLIGHT_DEV"."MDT_MANDANT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."ORG_UNIT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."ORG_UNIT_CHECK_OUT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."ORG_UNIT_REL_TYPE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."ORG_UNIT_TYPE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."PAY_PAYMENT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."PAY_PAYMENT_TYPE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."PLA_ENGINE_TYPE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."REL_AIRPORT_LOCATION" cascade constraints;
DROP TABLE "FLIGHT_DEV"."REL_BORD_LOG_ENTRY_PAY" cascade constraints;
DROP TABLE "FLIGHT_DEV"."REL_CONTACT_ADDRESS" cascade constraints;
DROP TABLE "FLIGHT_DEV"."REL_CONTACT_BANKACCOUNT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."REL_DOC_CONTACT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."REL_DOC_FLIGHT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."REL_DOC_HANGAR" cascade constraints;
DROP TABLE "FLIGHT_DEV"."REL_DOC_PLANE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."REL_DOC_TYPE_USAGE_TYPE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."REL_INV_PL_FLI_CH" cascade constraints;
DROP TABLE "FLIGHT_DEV"."REL_ORG_UNIT_CON" cascade constraints;
DROP TABLE "FLIGHT_DEV"."REL_ORG_UNIT_CON_ORG_REL_TYPE" cascade constraints;
DROP TABLE "FLIGHT_DEV"."REL_PAY_PLANE_FLI_CH" cascade constraints;
DROP TABLE "FLIGHT_DEV"."REL_PLANE_FLIGHT" cascade constraints;
DROP TABLE "FLIGHT_DEV"."REL_PLANE_FLIGHT_CHARTERER" cascade constraints;
DROP TABLE "FLIGHT_DEV"."RES_RESERVATION" cascade constraints;
DROP VIEW "FLIGHT_DEV"."V_ADR";
DROP VIEW "FLIGHT_DEV"."V_BOR_BORD_LOG";
DROP VIEW "FLIGHT_DEV"."V_CON_DOC_EXISTS";
DROP VIEW "FLIGHT_DEV"."V_DOC_MISS_INVAL";
DROP VIEW "FLIGHT_DEV"."V_FLI_FLIGHT";
--------------------------------------------------------
--  DDL for Sequence ADR_ADDRESS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ADR_ADDRESS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ADR_ADDRESS_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ADR_ADDRESS_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ADR_CITY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ADR_CITY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ADR_CITY_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ADR_CITY_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ADR_COUNTRY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ADR_COUNTRY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ADR_COUNTRY_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ADR_COUNTRY_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence APL_ENGINE_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."APL_ENGINE_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence APL_MAINT_PROGR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."APL_MAINT_PROGR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence APL_MAINT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."APL_MAINT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence APL_PLANE_MODELL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."APL_PLANE_MODELL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence APL_PLANE_MODELL_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."APL_PLANE_MODELL_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence APL_PLANE_MODELL_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."APL_PLANE_MODELL_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence APL_PLANE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."APL_PLANE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence APL_PLANE_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."APL_PLANE_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence APL_PLANE_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."APL_PLANE_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence APL_PLANE_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."APL_PLANE_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence APL_PLANE_TYPE_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."APL_PLANE_TYPE_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence APL_PLANE_TYPE_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."APL_PLANE_TYPE_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ARP_AIRPORT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ARP_AIRPORT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ARP_AIRPORT_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ARP_AIRPORT_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BAK_BANKACCOUNT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."BAK_BANKACCOUNT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BAK_BANKACCOUNT_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."BAK_BANKACCOUNT_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BAS_BASIC_GRP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."BAS_BASIC_GRP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 45 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BAS_BASIC_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."BAS_BASIC_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BAS_BASIC_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."BAS_BASIC_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BAS_BASIC_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."BAS_BASIC_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BOR_BORD_LOG_ENTRY_ADD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY_ADD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BOR_BORD_LOG_ENTRY_ADD_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY_ADD_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BOR_BORD_LOG_ENTRY_GRP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY_GRP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BOR_BORD_LOG_ENTRY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BOR_BORD_LOG_ENTRY_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."BOR_BORD_LOG_ENTRY_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BOR_BORD_LOG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."BOR_BORD_LOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BOR_BORD_LOG_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."BOR_BORD_LOG_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BOR_BORD_LOG_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."BOR_BORD_LOG_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 67 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BOR_BORD_LOG_SEQ3
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."BOR_BORD_LOG_SEQ3"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COM_COMPANY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."COM_COMPANY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CON_CONTACT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."CON_CONTACT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CON_CONTACT_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."CON_CONTACT_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CON_CONTACT_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."CON_CONTACT_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COST_COST_GRP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."COST_COST_GRP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 9 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEPT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."DEPT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 50 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DOC_DOCUMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."DOC_DOCUMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DOC_DOCUMENT_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."DOC_DOCUMENT_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DOC_DOCUMENT_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."DOC_DOCUMENT_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DOC_DOCUMENT_TYPE_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."DOC_DOCUMENT_TYPE_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DOC_USAGE_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."DOC_USAGE_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DOC_USAGE_TYPE_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."DOC_USAGE_TYPE_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."EMP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 8000 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FLI_FLIGHT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."FLI_FLIGHT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FLI_FLIGHT_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."FLI_FLIGHT_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FLI_FLIGHT_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."FLI_FLIGHT_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MDT_MANDANT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."MDT_MANDANT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MDT_MANDANT_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."MDT_MANDANT_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MDT_MANDANT_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."MDT_MANDANT_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORG_ORG_UNIT_REL_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ORG_ORG_UNIT_REL_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORG_ORG_UNIT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ORG_ORG_UNIT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORG_ORG_UNIT_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ORG_ORG_UNIT_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORG_ORG_UNIT_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ORG_ORG_UNIT_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORG_UNIT_CHECK_OUT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ORG_UNIT_CHECK_OUT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORG_UNIT_REL_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ORG_UNIT_REL_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORG_UNIT_REL_TYPE_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ORG_UNIT_REL_TYPE_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORG_UNIT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ORG_UNIT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORG_UNIT_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ORG_UNIT_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORG_UNIT_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ORG_UNIT_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORG_UNIT_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."ORG_UNIT_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REL_BORD_LOG_ENTRY_PAY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."REL_BORD_LOG_ENTRY_PAY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REL_CONTACT_ADDRESS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."REL_CONTACT_ADDRESS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REL_CONTACT_BANKACCOUNT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."REL_CONTACT_BANKACCOUNT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REL_DOC_CONTACT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."REL_DOC_CONTACT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REL_DOC_TYPE_USAGE_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."REL_DOC_TYPE_USAGE_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 65 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REL_ORG_UNIT_CON_CON_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."REL_ORG_UNIT_CON_CON_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REL_ORG_UNIT_CON_ORG_REL_TYPE1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."REL_ORG_UNIT_CON_ORG_REL_TYPE1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REL_ORG_UNIT_CON_ORG_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."REL_ORG_UNIT_CON_ORG_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REL_ORG_UNIT_CON_ORG_TYPE_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."REL_ORG_UNIT_CON_ORG_TYPE_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REL_ORG_UNIT_CON_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."REL_ORG_UNIT_CON_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REL_ORG_UNIT_CONTACT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."REL_ORG_UNIT_CONTACT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REL_ORG_UNIT_CONTACT_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."REL_ORG_UNIT_CONTACT_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REL_ORG_UNIT_CONTACT_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."REL_ORG_UNIT_CONTACT_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REL_ORG_UNIT_ORG_REL_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."REL_ORG_UNIT_ORG_REL_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REL_PLANE_FLIGHT_CHARTERER_SE
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."REL_PLANE_FLIGHT_CHARTERER_SE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REL_PLANE_FLIGHT_CHARTERER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."REL_PLANE_FLIGHT_CHARTERER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REL_PLANE_FLIGHT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."REL_PLANE_FLIGHT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence RES_RESERVATION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLIGHT_DEV"."RES_RESERVATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ADR_ADDRESS
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."ADR_ADDRESS" 
   (	"PK_ADR_ADDRESS" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"STREET" VARCHAR2(4000 BYTE), 
	"STREET_NO" VARCHAR2(20 BYTE), 
	"ZIP_CODE" VARCHAR2(20 BYTE), 
	"FK_ADR_CITY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADR_CITY
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."ADR_CITY" 
   (	"PK_ADR_CITY" NUMBER, 
	"CITY" VARCHAR2(4000 BYTE), 
	"FK_ADR_COUNTRY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADR_COUNTRY
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."ADR_COUNTRY" 
   (	"PK_ADR_COUNTRY" NUMBER, 
	"COUNTRY" VARCHAR2(4000 BYTE), 
	"PHONE_CODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table APL_ENGINE_TYPE
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."APL_ENGINE_TYPE" 
   (	"PK_APL_ENGINE_TYPE" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"ENGINE_TYPE" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table APL_MAINT
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."APL_MAINT" 
   (	"PK_APL_MAINT" NUMBER, 
	"INSP" VARCHAR2(4000 BYTE), 
	"DATE_CALC" DATE, 
	"DATE_PLANNED" DATE, 
	"DATE_DONE" DATE, 
	"FK_APL_PLANE" NUMBER, 
	"CREATED_AT" DATE, 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"MODIFIED_AT" DATE, 
	"PRICE_NET_PLANNED" NUMBER, 
	"PRICE_NET_FINAL" NUMBER, 
	"PRICE_BR_PLANNED" NUMBER, 
	"PRICE_TAX_PLANNED" NUMBER, 
	"PRICE_TAX_FINAL" NUMBER, 
	"PRICE_CURR" NUMBER, 
	"PRICED_BR_FINAL" NUMBER, 
	"MODIFIED_BY" VARCHAR2(20 BYTE), 
	"FK_APL_MAINT_PROGR" NUMBER, 
	"FK_MDT_MANDANT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table APL_MAINT_PROGR
--------------------------------------------------------

  CREATE TABLE "FLIGHT_DEV"."APL_MAINT_PROGR" 
   (	"PK_APL_MAINT_PROGR" NUMBER, 
	"FK_MDT_MANDANT" NUMBER, 
	"MAINT_PROGR" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
